### PR TITLE
refactor codebase structure

### PR DESCRIPTION
**Pull request by Yan-ni**
Hello,

I took some interest into your project recently and I would like to contribute with a refactoring of the project.

This PR aims to make the project follow some best practices and restructures/refactor the codebase.

Here are the total changes changes upon this PR:

- remove `package-lock.json` from `.gitignore` since it is not supposed to be ignored.
- add start script in the `package.json`
- regroup source code in one directory `src/`
- add environment variables `PORT` for the server port. (it’s easier this way to change it instead of changing it in the code everytime)
- add an `example.env` to give an example of all the environment variables required by the script.
- add the `dotenv` package to find and load the environment variables from `.env` file in development evironment.
- create `util/` folder for all the utility functions.
- create `database/` folder to hold all the database logic (this should also be broken down further)
- create `routes/` folder to hold all the routes logic (this should hold only the routes logic, but for now it also holds the controllers)

Let me know, if you need me in anything.

In case this PR gets accepted I al willing to help breakdown the rest of the code into more maintainable parts.

### CODE REVIEW

**Comment by YacineAi** [comment]
Hello Anis,

Thank you for your contribution. I will review it and see what I can approve.

- I am ignoring package-lock.json because it is not necessary for Render.com.
- The start command is not set because I am using the run command node index.js in Render.
- For small bot code, regrouping isn’t necessary, but I will consider it.
- Environment variables are being set in Render.com.
- Mainly, this repo isn’t user-driven; it is only meant to be deployed using Render.com.

If you're interested, I have a bigger codebase we can discuss, and I'd appreciate any advice you can offer.

Thank you so much.

**Comment by Yan-ni** [comment]
Hello Yacine,

I'd like to start by saying that you don't owe me any explanation, and that I contributed to what I believe was poorly made/coded. And your argument that you don't do something because it's not mandatory isn't so solid and will only lead you to your doom.

And regarding the offer to contribute to another bigger codebase I'd love to do so but only after this pr will see the light of day.

Thank you.

**Comment by Yan-ni** [comment]
Hello @YacineAi ,

I see that this PR has a merge conflict, is it possible to get a merge date so I may fix it in time?

Thanks.

**Review by YacineAi — CHANGES_REQUESTED** [review]
Handlers are missing onMessage and onPostBack. They are essential for the project to work.

**Review by YacineAi — APPROVED** [review]

**Pull request merged**
